export const ON_GET_ALL_EVENTS_REQUESTED = 'ON_GET_ALL_EVENTS_REQUESTED';
export const ON_GET_ALL_EVENTS_SUCCEEDED = 'ON_GET_ALL_EVENTS_SUCCEEDED';
export const ON_GET_ALL_EVENTS_FAILED = 'ON_GET_ALL_EVENTS_FAILED';

export const ON_GET_REPORTS_BY_ID_REQUESTED = 'ON_GET_REPORTS_BY_ID_REQUESTED';
export const ON_GET_REPORTS_BY_ID_SUCCEEDED = 'ON_GET_REPORTS_BY_ID_SUCCEEDED';
export const ON_GET_REPORTS_BY_ID_FAILED = 'ON_GET_REPORTS_BY_ID_FAILED';
