export const ON_GET_ALL_EVENTS_REQUESTED = 'ON_GET_ALL_EVENTS_REQUESTED';
export const ON_GET_ALL_EVENTS_SUCCEEDED = 'ON_GET_ALL_EVENTS_SUCCEEDED';
export const ON_GET_ALL_EVENTS_FAILED = 'ON_GET_ALL_EVENTS_FAILED';

export const ON_GET_EVENTS_FILTERED_BY_REQUESTED = 'ON_GET_EVENTS_FILTERED_BY_REQUESTED';
export const ON_GET_EVENTS_FILTERED_BY_SUCCEEDED = 'ON_GET_EVENTS_FILTERED_BY_SUCCEEDED';
export const ON_GET_EVENTS_FILTERED_BY_FAILED = 'ON_GET_EVENTS_FILTERED_BY_FAILED';
