export const ON_GET_EVENTS_FILTERED_BY_REQUESTED = 'ON_GET_EVENTS_FILTERED_BY_REQUESTED';
export const ON_GET_EVENTS_FILTERED_BY_SUCCEEDED = 'ON_GET_EVENTS_FILTERED_BY_SUCCEEDED';
export const ON_GET_EVENTS_FILTERED_BY_FAILED = 'ON_GET_EVENTS_FILTERED_BY_FAILED';

export const ON_CHANGE_BLOCK_EVENT_REQUESTED = 'ON_CHANGE_BLOCK_EVENT_REQUESTED';
export const ON_CHANGE_BLOCK_EVENT_SUCCEEDED = 'ON_CHANGE_BLOCK_EVENT_SUCCEEDED';
export const ON_CHANGE_BLOCK_EVENT_FAILED = 'ON_CHANGE_BLOCK_EVENT_FAILED';
