export const USER_ON_INITIALIZE_REQUESTED = 'USER_ON_INITIALIZE_REQUESTED';
export const USER_ON_INITIALIZE_SUCCEEDED = 'USER_ON_INITIALIZE_SUCCEEDED';
export const USER_ON_INITIALIZE_FAILED = 'USER_ON_INITIALIZE_FAILED';

export const USER_ON_LOGIN_REQUESTED = 'USER_ON_LOGIN_REQUESTED';
export const USER_ON_LOGIN_SUCCEEDED = 'USER_ON_LOGIN_SUCCEEDED';
export const USER_ON_LOGIN_FAILED = 'USER_ON_LOGIN_FAILED';

export const ON_GET_ALL_USERS_REQUESTED = 'ON_GET_ALL_USERS_REQUESTED';
export const ON_GET_ALL_USERS_SUCCEEDED = 'ON_GET_ALL_USERS_SUCCEEDED';
export const ON_GET_ALL_USERS_FAILED = 'ON_GET_ALL_USERS_FAILED';

export const ON_GET_ALL_ORGANIZERS_REQUESTED = 'ON_GET_ALL_ORGANIZERS_REQUESTED';
export const ON_GET_ALL_ORGANIZERS_SUCCEEDED = 'ON_GET_ALL_ORGANIZERS_SUCCEEDED';
export const ON_GET_ALL_ORGANIZERS_FAILED = 'ON_GET_ALL_ORGANIZERS_FAILED';

export const USER_ON_LOGOUT = 'USER_ON_LOGOUT';

export const ON_CHANGE_BLOCK_REQUESTED = 'ON_CHANGE_BLOCK_REQUESTED';
export const ON_CHANGE_BLOCK_SUCCEEDED = 'ON_CHANGE_BLOCK_SUCCEEDED';
export const ON_CHANGE_BLOCK_FAILED = 'ON_CHANGE_BLOCK_FAILED';
