export const USER_ON_LOGIN_REQUESTED = 'USER_ON_LOGIN_REQUESTED';
export const USER_ON_LOGIN_SUCCEEDED = 'USER_ON_LOGIN_SUCCEEDED';
export const USER_ON_LOGIN_FAILED = 'USER_ON_LOGIN_FAILED';

export const EVENT_ON_GET_ALL_USERS_REQUESTED = 'EVENT_ON_GET_ALL_USERS_REQUESTED';
export const EVENT_ON_GET_ALL_USERS_SUCCEEDED = 'EVENT_ON_GET_ALL_USERS_SUCCEEDED';
export const EVENT_ON_GET_ALL_USERS_FAILED = 'EVENT_ON_GET_ALL_USERS_FAILED';

export const EVENT_ON_GET_ALL_ORGANIZERS_REQUESTED = 'EVENT_ON_GET_ALL_ORGANIZERS_REQUESTED';
export const EVENT_ON_GET_ALL_ORGANIZERS_SUCCEEDED = 'EVENT_ON_GET_ALL_ORGANIZERS_SUCCEEDED';
export const EVENT_ON_GET_ALL_ORGANIZERS_FAILED = 'EVENT_ON_GET_ALL_ORGANIZERS_FAILED';

export const USER_ON_LOGOUT = 'USER_ON_LOGOUT';
